---
test:
  train2:
#    lr: 0.0001
    steps_per_epoch: 1
---
mol/lj:
  train2:
    data_path: '/data/public/rw/LJSpeech-1.0_processed/*.wav'
  convert:
    batch_size: 3
    emphasis_magnitude: 1.3
---
mol/lj/2:
  train2:
    data_path: '/data/public/rw/LJSpeech-1.0_processed/*.wav'
    hidden_units: 512  # alias: E
    num_banks: 8
    num_highway_blocks: 16
    norm_type: 'ins'  # a normalizer function. value: bn, ln, ins, or None
    dropout_rate: 0
  convert:
    batch_size: 3
    emphasis_magnitude: 1.3
---
mol/arctic:
  convert:
    batch_size: 3
    lr: 0.0001
---
mol/iu:
  train2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
    lr: 0.0001
  convert:
    data_path: '/data/private/vc/datasets/test/2018.wav'
    batch_size: 1
    emphasis_magnitude: 1.3